services:

  ##############
  # MEDIA SERVER
  ##############

  rms:
    image: pixelotes/rms:arm64
    container_name: rms
    profiles: ["rms"]
    restart: unless-stopped
    ports:
      - "8096:8082"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
      - "${MEDIA_DIR}:/app/media"
      - "./rms/config:/app/config"
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 16m

  ###########
  # HOMEPAGE
  ###########

  dashboarr:
    image: pixelotes/dashboarr:arm64
    container_name: dashboarr
    profiles: ["dashboarr"]
    ports:
      - "3000:80"
    volumes:
      - ./dashboarr/services.json:/var/www/localhost/htdocs/services.json:ro
    deploy:
      resources:
        limits:
          memory: 8m
        reservations:
          memory: 6m
    restart: unless-stopped

  #################
  # TORRENT CLIENT
  #################

  tango:
    image: pixelotes/tango:arm64
    container_name: tango
    profiles: ["tango"]
    restart: unless-stopped
    ports:
      - "7246:7246"
      - "6881:6881"
    volumes:
      - "./tango/config.yaml:/tango/config.yaml"
      - "./tango/session:/tango/session"
      - "${BASE_DIR}:/storage"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    deploy:
      resources:
        limits:
          memory: 192m
          cpus: "1.0"
        reservations:
          memory: 64m

  #################
  # INDEXER MANAGER
  #################

  scarf:
    image: pixelotes/scarf:arm64
    container_name: scarf
    profiles: ["scarf"]
    ports:
      - "8080:8080"
    volumes:
      - "./scarf/data:/app/data"
      - "./scarf/definitions:/app/definitions"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "WEB_UI=true"
      - "DEBUG=false"
      - "DB_PATH=/app/data/indexer-cache.db"
      - "UI_PASSWORD=${SCARF_UI_PASSWORD}"
      - "SKIP_TLS_VERIFY=true"
      - "JWT_SECRET=${SCARF_JWT_SECRET}"
      - "DEFAULT_API_LIMIT=300"
      - "CACHE_TTL=30m"
      - "ENABLE_CRONJOBS=false"
      - "CACHE_ENABLED=true"
      - "MAX_CACHE_SIZE_MB=32"
      - "MAX_CONCURRENT_SEARCHES=3"
    deploy:
      resources:
        limits:
          memory: 64m
        reservations:
          memory: 16m
    restart: unless-stopped

  ##################
  # MEDIA DOWNLOADER
  ##################

  reel:
    image: pixelotes/reel:arm64
    container_name: reel
    profiles: ["reel"]
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - "./reel/config:/app/config"
      - "./reel/data:/app/data"
      - "${BASE_DIR}:/storage"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    deploy:
      resources:
        limits:
          memory: 64m
        reservations:
          memory: 16m

  ##############
  # MUSIC SERVER
  ##############

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    profiles: ["navidrome"]
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "ND_SCANSCHEDULE=1h"
      - "ND_LOGLEVEL=info"
      - "ND_BASEURL="
    volumes:
      - "./navidrome:/data"
      - "${MEDIA_DIR}/Music:/music:ro"
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 192m

  ##############
  # MANGA READER
  ##############

  suika:
    image: pixelotes/suika:arm64
    container_name: suika
    profiles: ["suika"]
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
      - "./suika/config:/app/config"
      - "${MEDIA_DIR}/Manga:/app/media:ro"
    deploy:
      resources:
        limits:
          memory: 192m
        reservations:
          memory: 8m
